### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED 

### ISSUE THREAD

**Issue by cdliang11** [ZhengkunTian/OpenTransformer#3]
Traceback (most recent call last):
  File "run.py", line 56, in <module>
    main(cmd_args)
  File "run.py", line 38, in main
    trainer.train(train_dataset=train_dataset)
  File "/home/Liangcd/code/pytorch/openTransformer/OpenTransformer-aishell/otrans/train.py", line 91, in train
    train_loss = self.train_one_epoch(epoch, train_loader.loader)
  File "/home/Liangcd/code/pytorch/openTransformer/OpenTransformer-aishell/otrans/train.py", line 138, in train_one_epoch
    loss = self.model(**batch)
  File "/home/Liangcd/anaconda3/envs/pyEnv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/Liangcd/code/pytorch/openTransformer/OpenTransformer-aishell/otrans/model/transformer.py", line 54, in forward
    logits, _ = self.decoder(target_in, targets_length, enc_states, enc_mask)
  File "/home/Liangcd/anaconda3/envs/pyEnv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/Liangcd/code/pytorch/openTransformer/OpenTransformer-aishell/otrans/decoder.py", line 44, in forward
    dec_output, dec_mask = block(dec_output, dec_mask, memory, memory_mask)
  File "/home/Liangcd/anaconda3/envs/pyEnv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/Liangcd/code/pytorch/openTransformer/OpenTransformer-aishell/otrans/layer.py", line 116, in forward
    x = residual + self.dropout3(self.feed_forward(x))
  File "/home/Liangcd/anaconda3/envs/pyEnv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/Liangcd/code/pytorch/openTransformer/OpenTransformer-aishell/otrans/module.py", line 109, in forward
    x = self.w_1(x)
  File "/home/Liangcd/anaconda3/envs/pyEnv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/Liangcd/anaconda3/envs/pyEnv/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/Liangcd/anaconda3/envs/pyEnv/lib/python3.7/site-packages/torch/nn/functional.py", line 1372, in linear
    output = input.matmul(weight.t())
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

**Comment by ZhengkunTian** [comment]
Please reinstall a pytorch, like pytorch 1.4. This error has nothing with this code.
