### ISSUE TITLE
ValueError: Unknown type annotation: 'typing.Union[int, NoneType]'

### ISSUE THREAD

**Issue by ghost** [ZhengkunTian/OpenTransformer#7]
# 你好下载项目后，准备好数据后出现以下问题，请问是我哪里操作不对吗？
期待小伙伴的答复。

```
(venv3_zd) zd@ubuntu-server1:~/work_zd/Project_space/OpenTransformer$ python run.py -c egs/aishell/conf/transformer.yaml 
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    from otrans.model import Transformer
  File "/home/zd/work_zd/Project_space/OpenTransformer/otrans/model/__init__.py", line 1, in <module>
    from .transformer import Transformer
  File "/home/zd/work_zd/Project_space/OpenTransformer/otrans/model/transformer.py", line 3, in <module>
    from otrans.encoder import TransformerEncoder
  File "/home/zd/work_zd/Project_space/OpenTransformer/otrans/encoder.py", line 5, in <module>
    from otrans.utils import get_enc_padding_mask
  File "/home/zd/work_zd/Project_space/OpenTransformer/otrans/utils.py", line 6, in <module>
    from otrans.data import PAD
  File "/home/zd/work_zd/Project_space/OpenTransformer/otrans/data.py", line 5, in <module>
    import torchaudio as ta
  File "/home/zd/work_zd/venv3_zd/lib/python3.5/site-packages/torchaudio/__init__.py", line 8, in <module>
    from torchaudio import transforms, datasets, kaldi_io, sox_effects, compliance, _docs
  File "/home/zd/work_zd/venv3_zd/lib/python3.5/site-packages/torchaudio/transforms.py", line 6, in <module>
    from . import functional as F
  File "/home/zd/work_zd/venv3_zd/lib/python3.5/site-packages/torchaudio/functional.py", line 175, in <module>
    @torch.jit.script
  File "/home/zd/work_zd/venv3_zd/lib/python3.5/site-packages/torch/jit/__init__.py", line 1181, in script
    return _compile_function(fn=obj, qualified_name=qualified_name, _frames_up=_frames_up + 1, _rcb=_rcb)
  File "/home/zd/work_zd/venv3_zd/lib/python3.5/site-packages/torch/jit/__init__.py", line 1077, in _compile_function
    script_fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(fn))
  File "/home/zd/work_zd/venv3_zd/lib/python3.5/site-packages/torch/jit/annotations.py", line 58, in get_signature
    return parse_type_line(type_line)
  File "/home/zd/work_zd/venv3_zd/lib/python3.5/site-packages/torch/jit/annotations.py", line 110, in parse_type_line
    arg_types = [ann_to_type(ann) for ann in arg_ann]
  File "/home/zd/work_zd/venv3_zd/lib/python3.5/site-packages/torch/jit/annotations.py", line 110, in <listcomp>
    arg_types = [ann_to_type(ann) for ann in arg_ann]
  File "/home/zd/work_zd/venv3_zd/lib/python3.5/site-packages/torch/jit/annotations.py", line 227, in ann_to_type
    raise ValueError("Unknown type annotation: '{}'".format(ann))
ValueError: Unknown type annotation: 'typing.Union[int, NoneType]'
```

**Comment by ZhengkunTian** [comment]
不清楚，请检查一下数据格式或者torchaudio的安装。之前从没出现过相似的问题。

**Comment by Judonlee** [comment]
@ZhengkunTian 好的，谢谢。我再看看。有没有可能是python3.5的原因，我看你是在python3.6

**Comment by ZhengkunTian** [comment]
和这个应该没有关系，3.7我用着也没问题

**Comment by Judonlee** [comment]
@ZhengkunTian 哦，是torchaudio没安装好的原因。
`Python 3.5.2 (default, Jul 10 2019, 11:58:48) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torchaudio as ta
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zhudong/work_zd/venv3_zd/lib/python3.5/site-packages/torchaudio/__init__.py", line 8, in <module>
    from torchaudio import transforms, datasets, kaldi_io, sox_effects, compliance, _docs
  File "/home/zhudong/work_zd/venv3_zd/lib/python3.5/site-packages/torchaudio/transforms.py", line 6, in <module>
    from . import functional as F
  File "/home/zhudong/work_zd/venv3_zd/lib/python3.5/site-packages/torchaudio/functional.py", line 175, in <module>
    @torch.jit.script
  File "/home/zhudong/work_zd/venv3_zd/lib/python3.5/site-packages/torch/jit/__init__.py", line 1181, in script
    return _compile_function(fn=obj, qualified_name=qualified_name, _frames_up=_frames_up + 1, _rcb=_rcb)
  File "/home/zhudong/work_zd/venv3_zd/lib/python3.5/site-packages/torch/jit/__init__.py", line 1077, in _compile_function
    script_fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(fn))
  File "/home/zhudong/work_zd/venv3_zd/lib/python3.5/site-packages/torch/jit/annotations.py", line 58, in get_signature
    return parse_type_line(type_line)
  File "/home/zhudong/work_zd/venv3_zd/lib/python3.5/site-packages/torch/jit/annotations.py", line 110, in parse_type_line
    arg_types = [ann_to_type(ann) for ann in arg_ann]
  File "/home/zhudong/work_zd/venv3_zd/lib/python3.5/site-packages/torch/jit/annotations.py", line 110, in <listcomp>
    arg_types = [ann_to_type(ann) for ann in arg_ann]
  File "/home/zhudong/work_zd/venv3_zd/lib/python3.5/site-packages/torch/jit/annotations.py", line 227, in ann_to_type
    raise ValueError("Unknown type annotation: '{}'".format(ann))
ValueError: Unknown type annotation: 'typing.Union[int, NoneType]'
`

**Comment by ZhengkunTian** [comment]
嗯嗯，那就好

**Comment by ghost** [comment]
@ZhengkunTian 哦，是torchaudio没安装好的原因。
`Python 3.5.2 (default, Jul 10 2019, 11:58:48) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torchaudio as ta
Traceback (most recent call last):
   ...
    raise ValueError("Unknown type annotation: '{}'".format(ann))
ValueError: Unknown type annotation: 'typing.Union[int, NoneType]'
>>> 
`
